### ISSUE TITLE
[NEW FEATURE] Functional Dependency injection 

### ISSUE THREAD

**Issue by Mqzn** [VelixDevelopments/Imperat#1]
# Functional Dependency injection
Injecting fields as a dependency inside of command classes without the need for adding them to your constructor.

## Registering the dependency injector
```java
imperat.registerDependency(SomeDependency.class, ()-> new SomeDependencyClass());
```

## Injecting dependency example:
```java
@Command("test")
public final class TestCmd {
 
 @Dependency 
 private SomeDependencyClass field;
 
}

```

**Comment by iiAhmedYT** [comment]
It can't be final brother, it just can't

**Comment by Mqzn** [comment]
> It can't be final brother, it just can't

Yea, noticed the mistake here and edited it, thanks for telling me.

**Comment by Mqzn** [comment]
Added in Commit [Added Functional Dependency Injection](https://github.com/VelixDevelopments/Imperat/commit/89696bd098145cf99f71dbe3d2ebc10c2c9b8a94)
