### ISSUE TITLE
Random Debug message

### ISSUE THREAD

**Issue by Foxikle** [VelixDevelopments/Imperat#3]
On line 55 pf StringUtils there is a debug message that spams my server logs. I'm using the Bukkit provider, version 1.3.1
```java
System.out.println("ARGUMENT ONE LINE= '" + argumentsInOneLine + "'");
```

Thanks :)

**Comment by iiAhmedYT** [comment]
https://github.com/VelixDevelopments/Imperat/commit/bc1qee0gcaw92hcw2m5wv4pdknx433tjv4xm68n0up


It's already been addressed 11 days ago

**Comment by Mqzn** [comment]
Released, sorry for the delay <3
